chain = 1
protocol = "sonne"
comptroller_address = "0x60CF091cD3f50420d50fD7f707414d0DF4751C58"
provider_endpoint = "https://optimism-mainnet.infura.io/v3/4824addf02ec4a6c8618043ea418e6df"

[price_oracle]
kind = "sonne"
address = "0xEFc0495DA3E48c5A55F73706b249FD49d711A502"

[data_provider]
kind = "envio"
endpoint = "http://localhost:8080/v1/graphql"

[liquidator]
liquidator_address = "0xD9760ABad7021A0F64FC1f6fB4adB8f919A0a65d"
