chain = 1
protocol = "sonne"
comptroller_address = "0xE0B57FEEd45e7D908f2d0DaCd26F113Cf26715BF"
provider_endpoint = "wss://go.getblock.io/45f0fadb3c6a43a8a0a4d0c858fb24e9"

[price_oracle]
kind = "sonne"
address = "0x2424C30E589Caea191C06F41d1f5b90348dbeD7d"

[data_provider]
kind = "envio"
endpoint = "http://localhost:8080/v1/graphql"

[liquidator]
liquidator_address = "0xD9760ABad7021A0F64FC1f6fB4adB8f919A0a65d"
