chain = 1
protocol = "compoundv2"
comptroller_address = "0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B"
provider_endpoint = "https://optimism-mainnet.infura.io/v3/4824addf02ec4a6c8618043ea418e6df"

[price_oracle]
kind = "coingecko"
asset_platform = "ethereum"
endpoint = "https://api.coingecko.com/api/v3"

[data_provider]
kind = "envio"
endpoint = "googoogaga"

[liquidator]
liquidator_address = "0xD9760ABad7021A0F64FC1f6fB4adB8f919A0a65d"
