chain = 1
protocol = "sonne"
comptroller_address = "0x60CF091cD3f50420d50fD7f707414d0DF4751C58"
provider_endpoint = "wss://go.getblock.io/45f0fadb3c6a43a8a0a4d0c858fb24e9"

[price_oracle]
kind = "sonne"
address = "0x3176fA5060033a5d781b29De50D4A0f9E3d14F8F"

[data_provider]
kind = "envio"
endpoint = "http://localhost:8080/v1/graphql"

[liquidator]
liquidator_address = "0xD9760ABad7021A0F64FC1f6fB4adB8f919A0a65d"
